/** @type {import('tailwindcss').Config} */
tailwind.config = {
    darkMode: "class",
    theme: {
        extend: {
            "colors": {
                "inverse-primary": "#beffdc",
                "surface-variant": "#f2d9bc",
                "on-tertiary-fixed": "#003d50",
                "on-surface-variant": "#685948",
                "on-primary-container": "#246147",
                "inverse-on-surface": "#ac9a86",
                "on-error-container": "#570008",
                "secondary-fixed": "#ffca3d",
                "on-secondary-container": "#5b4400",
                "on-surface": "#382d1e",
                "inverse-surface": "#150c03",
                "tertiary-container": "#a3e0fc",
                "on-secondary-fixed-variant": "#664d00",
                "on-secondary-fixed": "#433200",
                "tertiary-fixed-dim": "#95d2ee",
                "surface-container-low": "#ffeedd",
                "primary-dim": "#1b5a40",
                "surface-container-lowest": "#ffffff",
                "on-background": "#382d1e",
                "secondary-container": "#ffca3d",
                "on-primary-fixed": "#0a4f36",
                "on-error": "#ffefee",
                "outline-variant": "#bdaa95",
                "background": "#fff5ec",
                "surface-dim": "#ead0b2",
                "error-container": "#fb5151",
                "error": "#b31b25",
                "secondary-dim": "#654c00",
                "tertiary": "#20627b",
                "tertiary-fixed": "#a3e0fc",
                "surface": "#fff5ec",
                "primary-fixed": "#b9f9d6",
                "surface-container": "#fce4ca",
                "surface-container-highest": "#f2d9bc",
                "secondary-fixed-dim": "#f0bd2c",
                "on-tertiary-container": "#005169",
                "error-dim": "#9f0519",
                "outline": "#847462",
                "primary-container": "#b9f9d6",
                "on-tertiary": "#e4f5ff",
                "on-primary": "#c8ffe0",
                "primary-fixed-dim": "#abebc8",
                "secondary": "#735700",
                "tertiary-dim": "#0b566e",
                "surface-bright": "#fff5ec",
                "on-secondary": "#fff1d9",
                "primary": "#29664c",
                "on-tertiary-fixed-variant": "#145b73",
                "on-primary-fixed-variant": "#2f6c51",
                "surface-container-high": "#f7dfc3",
                "surface-tint": "#29664c"
            },
            "borderRadius": {
                "DEFAULT": "1rem",
                "lg": "2rem",
                "xl": "3rem",
                "full": "9999px"
            },
            "fontFamily": {
                "headline": ["Plus Jakarta Sans"],
                "body": ["Be Vietnam Pro"],
                "label": ["Be Vietnam Pro"]
            }
        },
    },
}
